import streamlit as st
import sys, os
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from ml_engine import init_models, detect_weak_subjects

DIFFICULTY_MAP = {
    "critical":  "beginner tutorial explained simply",
    "weak":      "explained step by step tutorial",
    "moderate":  "practice problems solved",
    "strong":    "advanced concepts deep dive",
}

SUBJECT_CHANNELS = {
    "machine learning": ["3Blue1Brown", "StatQuest", "Sentdex", "Andrej Karpathy"],
    "data structures":  ["Abdul Bari", "CS Dojo", "Back To Back SWE", "NeetCode"],
    "algorithms":       ["Abdul Bari", "WilliamFiset", "NeetCode", "MIT OpenCourseWare"],
    "python":           ["Corey Schafer", "Tech With Tim", "Sentdex", "mCoding"],
    "networks":         ["PowerCert Animated Videos", "NetworkChuck", "Professor Messer"],
    "database":         ["Caleb Curry", "CMU Database Group", "Socratica"],
    "mathematics":      ["3Blue1Brown", "PatrickJMT", "Khan Academy", "Professor Leonard"],
    "operating systems":["Neso Academy", "Gate Smashers", "Jenny's Lectures"],
    "default":          ["Khan Academy", "CrashCourse", "MIT OpenCourseWare", "TED-Ed"],
}

def _build_search_url(query: str) -> str:
    return "https://www.youtube.com/results?search_query=" + query.replace(" ", "+")

def _build_query(subject: str, topic: str, tier: str) -> str:
    suffix = DIFFICULTY_MAP.get(tier, "tutorial")
    q = subject
    if topic:
        q += f" {topic}"
    return f"{q} {suffix}"

def _get_channels(subject: str) -> list:
    s = subject.lower()
    for key in SUBJECT_CHANNELS:
        if key in s:
            return SUBJECT_CHANNELS[key]
    return SUBJECT_CHANNELS["default"]

def _render_resource_card(title: str, channel: str, url: str, tier: str, description: str = ""):
    tier_color = {"critical":"#7c3aed","weak":"#ef4444","moderate":"#f59e0b","strong":"#22c55e"}.get(tier,"#64748b")
    st.markdown(f"""
    <a href="{url}" target="_blank" style="text-decoration:none;">
        <div class='card' style='border-left:3px solid {tier_color}; cursor:pointer; transition:all 0.2s;'
             onmouseover="this.style.transform='translateX(4px)'"
             onmouseout="this.style.transform='translateX(0)'">
            <div style='display:flex; align-items:flex-start; gap:0.8rem;'>
                <div style='font-size:1.5rem; min-width:32px;'>▶️</div>
                <div style='flex:1;'>
                    <div style='font-family:Syne; color:#e2e8f0; font-weight:600; font-size:0.9rem;'>{title}</div>
                    <div style='color:#64748b; font-size:0.78rem; margin-top:0.2rem;'>
                        📺 {channel}
                        {f' · <span style="color:#94a3b8;">{description}</span>' if description else ''}
                    </div>
                </div>
                <span class='pill' style='border-color:{tier_color}; color:{tier_color}; background:rgba(0,0,0,0.3); white-space:nowrap;'>
                    {tier}
                </span>
            </div>
        </div>
    </a>
    """, unsafe_allow_html=True)

def show():
    st.markdown("""
    <div style='font-family:Syne; font-size:2rem; font-weight:800; color:#e2e8f0;'>
        📺 YouTube Resources
    </div>
    <div style='color:#64748b; margin-bottom:1.5rem;'>
        ML-powered resource recommendations based on your weakness tier — 
        curated channels matched to your subject & difficulty level
    </div>
    """, unsafe_allow_html=True)

    tab1, tab2 = st.tabs(["🔍 Search by Subject", "🤖 ML-Powered Recommendations"])

    # ── TAB 1: Manual Search ────────────────────────────────────────
    with tab1:
        c1, c2 = st.columns(2)
        subject_input = c1.text_input("Subject / Topic", placeholder="e.g. Machine Learning, Neural Networks")
        tier_input    = c2.selectbox("Your Level for this Topic", ["critical", "weak", "moderate", "strong"], index=1)
        topic_detail  = st.text_input("Specific Topic (optional)", placeholder="e.g. Backpropagation, Binary Trees")

        yt_api_key = st.text_input("YouTube API Key (optional — for live results)", 
                                    type="password", placeholder="AIza...",
                                    help="Get a free key from console.cloud.google.com. Without it, curated search links are shown.")

        if st.button("🔍 Find Resources", key="find_yt", use_container_width=True):
            if not subject_input:
                st.warning("Please enter a subject.")
                return

            query = _build_query(subject_input, topic_detail, tier_input)
            channels = _get_channels(subject_input)

            st.markdown(f"""
            <div class='card' style='margin-bottom:1rem;'>
                <div style='color:#64748b; font-size:0.8rem;'>Search query generated by ML:</div>
                <div style='font-family:Syne; color:#a78bfa; font-weight:700; font-size:1rem; margin-top:0.3rem;'>"{query}"</div>
            </div>
            """, unsafe_allow_html=True)

            # If API key provided, show direct YouTube link (actual API call needs server)
            if yt_api_key:
                st.info("🔑 API key detected! In the full deployment, live YouTube results would appear here. For now, curated resources are shown.")

            st.markdown(f"<div style='font-family:Syne; color:#e2e8f0; font-weight:700; margin-bottom:0.5rem;'>📺 Curated Resources for: {subject_input}</div>", unsafe_allow_html=True)

            # Direct search links
            _render_resource_card(
                title=f"Search YouTube: {query}",
                channel="YouTube Search",
                url=_build_search_url(query),
                tier=tier_input,
                description="Best match for your level"
            )

            # Recommended channels
            st.markdown(f"<div style='font-family:Syne; color:#94a3b8; font-weight:600; margin:1rem 0 0.5rem; font-size:0.9rem;'>⭐ Top Channels for {subject_input}</div>", unsafe_allow_html=True)
            for ch in channels:
                ch_query = f"{ch} {subject_input} {topic_detail or ''}".strip()
                _render_resource_card(
                    title=f"{ch} — {subject_input}",
                    channel=ch,
                    url=_build_search_url(ch_query),
                    tier=tier_input,
                    description="Recommended channel"
                )

            # Khan Academy & practice
            st.markdown("<div style='font-family:Syne; color:#94a3b8; font-weight:600; margin:1rem 0 0.5rem; font-size:0.9rem;'>📚 Additional Resources</div>", unsafe_allow_html=True)
            extra = [
                ("Khan Academy", "https://www.khanacademy.org/search?query=" + subject_input.replace(" ", "+"), "Free world-class education"),
                ("MIT OpenCourseWare", "https://ocw.mit.edu/search/?q=" + subject_input.replace(" ", "+"), "Free university courses"),
                ("GeeksForGeeks", "https://www.geeksforgeeks.org/search/?q=" + subject_input.replace(" ", "+"), "CS tutorials & problems"),
            ]
            for name, url, desc in extra:
                st.markdown(f"""
                <a href="{url}" target="_blank" style="text-decoration:none;">
                    <div class='card' style='display:flex; justify-content:space-between; align-items:center; cursor:pointer;'>
                        <div>
                            <div style='font-family:Syne; color:#e2e8f0; font-weight:600; font-size:0.9rem;'>{name}</div>
                            <div style='color:#64748b; font-size:0.78rem;'>{desc}</div>
                        </div>
                        <span style='color:#a78bfa; font-size:1.2rem;'>→</span>
                    </div>
                </a>
                """, unsafe_allow_html=True)

    # ── TAB 2: ML-Powered Recommendations ──────────────────────────
    with tab2:
        st.markdown("""
        <div class='card'>
            <div style='font-family:Syne; color:#a78bfa; font-weight:700; margin-bottom:0.5rem;'>🤖 How it works</div>
            <div style='color:#94a3b8; font-size:0.85rem; line-height:1.6;'>
                LOHA uses the <b style='color:#e2e8f0;'>RandomForestClassifier</b> to detect your weakness tier 
                per subject, then tailors the search query difficulty: 
                <b style='color:#7c3aed;'>critical</b> → beginner tutorials, 
                <b style='color:#ef4444;'>weak</b> → step-by-step guides, 
                <b style='color:#f59e0b;'>moderate</b> → practice problems, 
                <b style='color:#22c55e;'>strong</b> → advanced deep dives.
            </div>
        </div>
        """, unsafe_allow_html=True)

        # Use weak_results from ML page if available
        if st.session_state.get("weak_results"):
            results = st.session_state["weak_results"]
            st.success(f"✅ Using ML weakness analysis for {len(results)} subjects from the AI Insights page!")
        else:
            st.info("💡 Run **Weak Topic Detector** in the AI Insights page first for personalized recommendations. Using defaults below.")
            results = [
                {"name": "Machine Learning", "weakness_tier": "moderate", "avg_score": 72, "target_score": 85},
                {"name": "Data Structures",  "weakness_tier": "weak",     "avg_score": 48, "target_score": 80},
                {"name": "Networks",         "weakness_tier": "strong",   "avg_score": 88, "target_score": 85},
            ]

        # Filter to show weak/critical first
        weak_first = sorted(results, key=lambda x: {"critical":0,"weak":1,"moderate":2,"strong":3}.get(x.get("weakness_tier","moderate"),2))

        for subj in weak_first:
            tier  = subj.get("weakness_tier", "moderate")
            name  = subj.get("name", "Subject")
            avg   = subj.get("avg_score", 0)
            target= subj.get("target_score", 80)
            tier_color = {"critical":"#7c3aed","weak":"#ef4444","moderate":"#f59e0b","strong":"#22c55e"}.get(tier,"#64748b")

            query   = _build_query(name, "", tier)
            channels= _get_channels(name)

            with st.expander(f"{'🚨' if tier=='critical' else '⚠️' if tier=='weak' else '📊' if tier=='moderate' else '✅'} {name}  ·  Avg: {avg:.0f}%  ·  Tier: {tier.upper()}", expanded=(tier in ["critical","weak"])):
                st.markdown(f"""
                <div style='background:rgba(0,0,0,0.3); border-radius:8px; padding:0.6rem 1rem; margin-bottom:0.8rem;'>
                    <span style='color:#64748b; font-size:0.8rem;'>ML Query: </span>
                    <span style='color:#a78bfa; font-size:0.85rem; font-style:italic;'>"{query}"</span>
                </div>
                """, unsafe_allow_html=True)

                # Primary search
                _render_resource_card(
                    title=f"🎯 Search YouTube: {query}",
                    channel="YouTube Search",
                    url=_build_search_url(query),
                    tier=tier,
                    description=f"Tailored for {tier} level"
                )

                # Practice query
                practice_q = f"{name} practice problems solved exercises"
                _render_resource_card(
                    title=f"📝 Practice Problems: {name}",
                    channel="YouTube Search",
                    url=_build_search_url(practice_q),
                    tier=tier,
                    description="Hands-on practice"
                )

                # Top channels
                for ch in channels[:3]:
                    _render_resource_card(
                        title=f"{ch}",
                        channel=ch,
                        url=_build_search_url(f"{ch} {name}"),
                        tier=tier,
                    )

        # Tips section
        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("""
        <div class='card'>
            <div style='font-family:Syne; color:#34d399; font-weight:700; margin-bottom:0.5rem;'>💡 Study Tips for Video Learning</div>
            <div style='color:#94a3b8; font-size:0.85rem; line-height:2;'>
                📌 <b style='color:#e2e8f0;'>Active watching:</b> Pause and try problems before seeing solutions<br>
                📝 <b style='color:#e2e8f0;'>Take notes:</b> Use Cornell method while watching<br>
                🔁 <b style='color:#e2e8f0;'>Spaced repetition:</b> Rewatch weak topics after 1, 3, 7 days<br>
                ⚡ <b style='color:#e2e8f0;'>Speed up:</b> Watch at 1.5x for topics you partially know<br>
                🎯 <b style='color:#e2e8f0;'>Targeted search:</b> Search "topic + your specific doubt"
            </div>
        </div>
        """, unsafe_allow_html=True)